-- Migration 012: Expand job_orders with full field set from Bullhorn SDK

BEGIN;

ALTER TABLE job_orders
    ADD COLUMN IF NOT EXISTS is_deleted             BOOLEAN,
    ADD COLUMN IF NOT EXISTS is_work_from_home      BOOLEAN,
    ADD COLUMN IF NOT EXISTS will_relocate          BOOLEAN,
    ADD COLUMN IF NOT EXISTS will_sponsor           BOOLEAN,
    ADD COLUMN IF NOT EXISTS date_last_modified     DATE,
    ADD COLUMN IF NOT EXISTS date_closed            DATE,
    ADD COLUMN IF NOT EXISTS date_end               DATE,
    ADD COLUMN IF NOT EXISTS start_date             DATE,
    ADD COLUMN IF NOT EXISTS employment_type        TEXT,
    ADD COLUMN IF NOT EXISTS type                   TEXT,
    ADD COLUMN IF NOT EXISTS source                 TEXT,
    ADD COLUMN IF NOT EXISTS on_site                TEXT,
    ADD COLUMN IF NOT EXISTS travel_requirements    TEXT,
    ADD COLUMN IF NOT EXISTS years_required         INTEGER,
    ADD COLUMN IF NOT EXISTS pay_rate               NUMERIC(14,4),
    ADD COLUMN IF NOT EXISTS client_bill_rate       NUMERIC(14,4),
    ADD COLUMN IF NOT EXISTS salary                 NUMERIC(14,4),
    ADD COLUMN IF NOT EXISTS salary_unit            TEXT,
    ADD COLUMN IF NOT EXISTS duration_weeks         NUMERIC(8,2),
    ADD COLUMN IF NOT EXISTS hours_per_week         NUMERIC(8,2),
    ADD COLUMN IF NOT EXISTS tax_status             TEXT,
    ADD COLUMN IF NOT EXISTS description            TEXT,
    ADD COLUMN IF NOT EXISTS public_description     TEXT,
    ADD COLUMN IF NOT EXISTS external_id            TEXT,
    ADD COLUMN IF NOT EXISTS report_to              TEXT,
    ADD COLUMN IF NOT EXISTS address1               TEXT,
    ADD COLUMN IF NOT EXISTS address2               TEXT,
    ADD COLUMN IF NOT EXISTS city                   TEXT,
    ADD COLUMN IF NOT EXISTS state                  TEXT,
    ADD COLUMN IF NOT EXISTS zip                    TEXT,
    ADD COLUMN IF NOT EXISTS client_contact_id      INTEGER,
    ADD COLUMN IF NOT EXISTS client_contact_first   TEXT,
    ADD COLUMN IF NOT EXISTS client_contact_last    TEXT,
    ADD COLUMN IF NOT EXISTS owner_first            TEXT,
    ADD COLUMN IF NOT EXISTS owner_last             TEXT,
    ADD COLUMN IF NOT EXISTS branch_id              INTEGER,
    ADD COLUMN IF NOT EXISTS branch_name            TEXT,
    ADD COLUMN IF NOT EXISTS custom_date1           DATE,
    ADD COLUMN IF NOT EXISTS custom_date2           DATE,
    ADD COLUMN IF NOT EXISTS custom_date3           DATE,
    ADD COLUMN IF NOT EXISTS custom_float1          NUMERIC(18,4),
    ADD COLUMN IF NOT EXISTS custom_float2          NUMERIC(18,4),
    ADD COLUMN IF NOT EXISTS custom_float3          NUMERIC(18,4),
    ADD COLUMN IF NOT EXISTS custom_int1            INTEGER,
    ADD COLUMN IF NOT EXISTS custom_int2            INTEGER,
    ADD COLUMN IF NOT EXISTS custom_int3            INTEGER,
    ADD COLUMN IF NOT EXISTS custom_text1           TEXT,
    ADD COLUMN IF NOT EXISTS custom_text2           TEXT,
    ADD COLUMN IF NOT EXISTS custom_text3           TEXT,
    ADD COLUMN IF NOT EXISTS custom_text4           TEXT,
    ADD COLUMN IF NOT EXISTS custom_text5           TEXT,
    ADD COLUMN IF NOT EXISTS custom_text6           TEXT,
    ADD COLUMN IF NOT EXISTS custom_text7           TEXT,
    ADD COLUMN IF NOT EXISTS custom_text8           TEXT,
    ADD COLUMN IF NOT EXISTS custom_text9           TEXT,
    ADD COLUMN IF NOT EXISTS custom_text10          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text11          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text12          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text13          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text14          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text15          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text16          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text17          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text18          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text19          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text20          TEXT,
    ADD COLUMN IF NOT EXISTS custom_text_block1     TEXT,
    ADD COLUMN IF NOT EXISTS custom_text_block2     TEXT,
    ADD COLUMN IF NOT EXISTS custom_text_block3     TEXT,
    ADD COLUMN IF NOT EXISTS custom_text_block4     TEXT,
    ADD COLUMN IF NOT EXISTS custom_text_block5     TEXT;

CREATE INDEX IF NOT EXISTS idx_job_orders_city  ON job_orders(city);
CREATE INDEX IF NOT EXISTS idx_job_orders_state ON job_orders(state);

COMMIT;
